### ISSUE TITLE
Error on Lazarus LEDREDON not found

### ISSUE THREAD

**Issue by eldonfsr** [alexx2000/lazcomport#1]
I compile on lazarus and send me this error resource LEDREDON not found, i try to find some thing like that on source files but i don't see nothing like that. when compile Miniterm example.

**Comment by levshx** [comment]
confirm > TComLed not work

I think the error is in  [lazcomport/Source/CPortCtl.pas](https://github.com/alexx2000/lazcomport/blob/master/Source/CPortCtl.pas "Вот")
TComLed.SelectLedBitmap

You might need to use the lazres resource linker for CPortImg.res

**Comment by alexx2000** [comment]
I hope fixed now.
